
### Create a room
POST {{chat}}/api/message/create
Authorization: {{BEARER}}
Content-Type: application/json

{
  "userId": 1,
  "roomId": 1,
  "text": "First text message"
}

### Get all messages
GET {{chat}}/api/message/all?roomId=1
Authorization: {{BEARER}}

### Delete message by id
DELETE {{chat}}/api/message?id=1
Authorization: {{BEARER}}
